### ISSUE TITLE
Warn user if there is nothing to export

### ISSUE THREAD

**Issue by thomthom** [SketchUp/sketchup-stl#156]
Instead of exporting an empty STL file if the model is empty or the Export Selected is checked and selection is empty it would be better to alert the user.

**Comment by jimfoltz** [comment]
What do you think - a single message, or separate messages tailored to either situation of "model empty" or "selection empty"? I just want to make the wording as clear as possible for everyone.

"There is nothing to export. Either the model or the selection is empty."
OR
"There is nothing to export. The model is empty."
"There is nothing to export. The selection is empty."

**Comment by jimfoltz** [comment]
wtf. Sigh.

**Comment by thomthom** [comment]
I think I lean toward the latter - specific for each scenario - as it aids the user better in what is expected based on the selected preferences. Though, any message is better than none.

**Comment by jimfoltz** [comment]
Before I start on this, here's an outline of the plan:

- Remove the validation proc that disables the "Export STL" menu item when the model is empty.   Since new warnings will be added to prevent export of an empty .stl file, there is less reason to disable the menu.  Also, I just don't like the disabled menu - there is no explaination why is is unavailable and no way to get an explaination.  

- When the user selects "Export STL" and the model is empty, display a warning, then exit.

- At the time the export dialog opens, automatically check or uncheck the "Export selected" option.  Make the assumption if the user  begins an export with something selected, the intention is to export only the selection.

**Comment by thomthom** [comment]
Sounds good to me.

The disabled menu issue is something I've read about a few times in terms of UX issues with the common convention of disabling. You echo what those article said, the user is unable to learn why the menu is disable.

One question about the selection, what if the selection is just edges or faces? Do we export just those? Or does it make sense to detect selected group/component instances and use that to determine the "Export selected" option?

**Comment by jimfoltz** [comment]
I looked at all the Pro exporters. Only the FBX and 3DS exporters had the option to export only the selection. Both of them went ahead and exported without a message if nothing was selected. I am not saying we should do the same, though. 

SketchUp also diasbles the Export > 3D Model menu when the model is empty.

**Comment by thomthom** [comment]
Ah, yes, the Exporter interface. I've been wanting to get that added for a long time. I'll see if I can bump that.
