### ISSUE TITLE
Seems to export files rotated 90º when previewed

### ISSUE THREAD

**Issue by jsejcksn** [SketchUp/sketchup-stl#162]
I'm previewing files with the built-in Quick Look in macOS 10.12.2.

When I export STL files from SketchUp in the default axis orientation, it looks like this:

<img width="150" alt="zup" src="https://cloud.githubusercontent.com/assets/868251/21284277/0912e714-c3dd-11e6-92dd-1b944ee173bf.png">

_z-up axis orientation_

<img width="211" alt="stl-zup" src="https://cloud.githubusercontent.com/assets/868251/21284341/17390994-c3de-11e6-9b77-270d15f9f33c.png">

_Quick Look preview_

That is also how output from Fusion 360 appears. **I think it looks really odd that the model starts out on its side like that.**

However, when I orient the y-axis upward in Fusion 360, it exports my STL like so:

<img width="150" alt="yup" src="https://cloud.githubusercontent.com/assets/868251/21284374/dbb79966-c3de-11e6-905c-b6c011ae2d2c.png">

_y-up axis orientation_

<img width="211" alt="stl-zup" src="https://cloud.githubusercontent.com/assets/868251/21284379/f38b51cc-c3de-11e6-95cd-d723e94df3a5.png">

_Quick Look preview_

But [doing the same thing in SketchUp](http://help.sketchup.com/en/article/3000102) doesn't change the orientation in the preview. **This is a more true representation of my model as I see it in the software.**

My SketchUp model is attached for reference.

[e.skp.zip](https://github.com/SketchUp/sketchup-stl/files/658644/e.skp.zip)

**Comment by thomthom** [comment]
This is a result of different applications using different axes for Up. SketchUp uses Z, sounds like Fusion 360 by default also use Z as Up. While Quick Look in OS-X uses Y.

When working with STL files most files I've used is Z up. Don't think I have many that is Y up.

Windows' preview window will display Z up:

![image](https://cloud.githubusercontent.com/assets/192418/21285579/b2e5c784-c43c-11e6-852b-9eb0caf476b0.png)

I didn't find any options for Z or Y up though. Do Quick Look have some options for that?

Another issue here is that the API until recently didn't provide access of the model's working axis. Which is why changing the axes in SU didn't work for the export. Taking that into account would be good.

Though for this particular Z/Y issues I think the better solution is to have an Export option. Though I wonder if Quick View is the odd one out here, with Y up for STL files. I'd like to compare a few files from Thingyverse etc.

**Comment by jsejcksn** [comment]
Hi @thomthom:

In a new install of Fusion 360, y-up is the default axis orientation.

QuickLook does not have any preferences because it is just a universal file preview tool. It is activated in macOS by pressing the spacebar when a file is selected and will give a visual preview of the contents if possible.

3D models (including STL files) can be opened natively in macOS in the Preview app. It also does not have any preferences related to up axis, although the Inspector (Info window) does display up axis if that information is embedded in a 3d model. I'm not sure if that's part of the STL spec or not—none of the STL files exported from SketchUp or Fusion 360 display information in that field in Preview, although the models exported from Fusion 360 are oriented differently depending on up axis. I have included a .zip of the STL files and here's a screenshot of the Inspector window of Preview:

<img width="320" alt="inspector" src="https://cloud.githubusercontent.com/assets/868251/21296888/5ae8e6d8-c53b-11e6-9064-3c802358cb1c.png">

[stl-f-export-test.zip](https://github.com/SketchUp/sketchup-stl/files/659694/stl-f-export-test.zip)

**Comment by thomthom** [comment]
STL format doesn't specify a standard for "up" as far as I can tell. Best is probably to add an import/export option for what axis is up.

**Comment by jsejcksn** [comment]
Checking in on this after >1 yr. What's the status—is it fixed, in the backlog, etc.? (I haven't tested since raising the issue.)

**Comment by thomthom** [comment]
SketchUp 2018 shipped with native STL importer/exporter. Both importer and exporter have options for Z/Y being up.

![image](https://user-images.githubusercontent.com/192418/40621387-d8602536-629c-11e8-96b4-54f71b4606e9.png)
