### ISSUE TITLE
Can't download Sketchup-STL RBZ

### ISSUE THREAD

**Issue by Aerilius** [SketchUp/sketchup-stl#172]
The following popped up in my inbox, sent from an anonymous disposable address. The author must have been aware of this very issue tracker but chose a unidirectional communication without admitting to me the right to interact, comment, resolve or even agree. I think it is a matter of fairness to pull this into a public discussion space.

> I came across your email address posted on the Sketchup-STL Github in a file called "LICENSE-CHANGE-20140312.md".
> 
> I'm trying to use Sketchup for the first time, and apparently I need to use your extension Sketchup-STL to export to STL.  I'm modifying a file I found on Thingiverse.
> 
> I am unable to download the file due to a cascading series of hurdles and failures.  The extension is locked behind a paywall, and creating an account does not seem to work for some reason.  The paywall requires PII (Personally Identifiable Information), and its clear that Sketchup and Trimble are both hungry for PII.
> 
> This PII paywall is against the terms of the MIT license, which says that the file must be available free of charge.
> 
> I've tried downloading the RBZ file from Github and I get a 404 error.
> 
> I do not monitor this email box, it's essentially a public mailbox.  Instead of replying, please just fix these things.
> 
> Thanks!

---

My wild guess is that there are two misconceptions: 
- The MIT license is not restrictive on the original authors who have as a prerequisite published the software hereby and in source code. Moreover it is permissive to users in that there is no obligation to publish modifications in source of binary form.
- There exists a login wall, not a paywall iff users choose to download from Extension Warehouse instead of Github.

---

Anyhow, the project owners could just conclude and close with a clarifying statement, nobody will object.

**Comment by thomthom** [comment]
Hi Andreas, I found the very same message.

It's unclear to me what hurdles the user have encountered. I hope the user haven't been faced with any malicious third party source that tries to charge for the extension.

I'm wondering if they tried to obtain it via Extension Warehouse or GitHub. When signing up for an account at Extension Warehouse there isn't any request for payment information. But when signing up for GitHub they might be trying to get the user to upgrade to a paid account. Maybe the confusion stems for that.

It's also unclear to me what RBZ download is giving 404 on GitHub. As far as I can tell, the RBZ files were never uploaded here. Only on Extension Warehouse.

Good initiative on opening a ticket here. Because the "please just fix these things" wasn't really something we can take actions on since they are user actions. Maybe the user will find this ticket, maybe no. Not much we can do without any means of communicating back.
